on:[push]
name:'Dependency Check scan'
description:'Runs dependency check on checked out code.'
inputs:
    Project-Name:
        required: true
    Source-Location:
        required: false
        default: '/github/workspace'    
    Report-Format:
        required: false
        default: 'ALL'
    Report-Location:
        required: false
        default: '/github/workspace/reports'
   Log-Name:
        required: false
        default: log.txt
runs: 
 using: 'docker'
 image: 'Dockerfile'
